### PR TITLE
Preserve defaults while decoding nested structs

### PR DESCRIPTION
**Pull request by Al2Klimov**
```yaml
---
a: A
#b: DEFAULT # already works
c:
  d: D
  #e: DEFAULT # was not DEFAULT, but "", now works
```

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@goccy Now it should work!

**Review by htriem — APPROVED** [review]
LGTM! 👍

**Comment by goccy** [comment]
@Al2Klimov 
Could you please describe this fixing in this PR description with example YAML.

**Comment by Al2Klimov** [comment]
@goccy Done.

**Comment by goccy** [comment]
@Al2Klimov Thank you ! LGTM

**Pull request merged**
