### PR TITLE
Fix quoted map key

### LINKED ISSUE #301: Unmarshalling a list of maps fails with "unexpected key name"
I got `unexpected key name` when I tried to unmarshal the following YAML.

```yaml
- "min": 1
  "max": 2
```

Here is the minimum code to reproduce.

### Code

```go
package main

import (
	"github.com/goccy/go-yaml"
	// "gopkg.in/yaml.v3" // No errors when using this
)

const yamlBody = `
- "min": 1
  "max": 2
`

func main() {
	var v []struct {
		Min int
		Max int
	}

	err := yaml.Unmarshal([]byte(yamlBody), &v)
	if err != nil {
		panic(err)
	}
}
```

Go Playground: https://go.dev/play/p/liMbShEkswO

### Outputs

```console
panic: [2:10] unexpected key name
>  2 | - "min": 1
   3 |   "max": 2
```

### Tested versions

- go 1.17, 1.18
- goccy/go-yaml: 1.9.5

### PR DESCRIPTION
**Pull request by goccy**
fix #301 

ref https://github.com/goccy/go-yaml/pull/327

### CODE REVIEW

**Review by braydonk — COMMENTED** [review]
This does look easier, however it looks like this will break on the following valid yaml:

```yaml
a:
  "b" : 1
  "c": 2
```
It would be good to add this as a test case, I should have added it in mine.

My proposal in #327 had something to check if the buffer is currently all whitespace, maybe including this would fix it?

**Comment by goccy** [comment]
@braydonk Thank you for your review ! You are right, I will try to make a fix that will take care of whitespace.

**Comment by goccy** [comment]
> I will try to make a fix that will take care of whitespace.

DONE.

**Review by braydonk — APPROVED** [review]
Good strategy! Looks good to me.

**Comment by goccy** [comment]
@braydonk Thank you for your review !! Merged.

**Pull request merged**
