### PR TITLE
Fixing Issue 186, scanner should account for newline characters when …

### PR DESCRIPTION
**Pull request by rspruyt-google**
…processing multi-line text. Without this source annotations line/column number (for this and all subsequent tokens) is inconsistent with plain text editors. e.g. https://github.com/goccy/go-yaml/issues/186. This addresses the issue specifically for single and double quote text only.

1.) We would have preferred to avoid introducing an additional state in the loop (isNewLine), but this requires placing the column marker to an invalid position (0) and believe it is safer not to do so. This is done to avoid potential bugs in the future if the loop exits before the column marker can be brought back in-bounds.

2.) We debated internally whether the slice sorting in the tests should be done through a helper function or not. We didn't feel a convenience function improved code readability to merit consolidation of the logic. If you disagree, lmk. We add the sort to be token order agnostic in our tests.

### CODE REVIEW

**Comment by goccy** [comment]
Thank you for the contribution ! 
I'm wondering if it will affect the behavior when processing YAML containing multiline with the printer package,
so could you add a test to the printer package as well ?

**Comment by rspruyt-google** [comment]
Added tests as requested, seeing what looks like a docker CI failure, maybe configuration related? https://app.circleci.com/pipelines/github/goccy/go-yaml/430/workflows/72ea66b8-0da8-43f3-ba4f-cf5d4a99910b/jobs/362

**Comment by rspruyt-google** [comment]
sync and had to add missing address missing name/email for CI checkout

**Comment by goccy** [comment]
@rspruyt-google Great !! Thank you !!

**Pull request merged**
