### PR TITLE
Allow ending document delimiter within tag values

### PR DESCRIPTION
**Pull request by wass3r**
closes https://github.com/goccy/go-yaml/issues/189

### CODE REVIEW

**Comment by wass3r** [comment]
We are unable to make the tests fail running inside the same `circleci/golang:1.15` image that your tset pipeline is using. Any thoughts?

**Comment by wass3r** [comment]
Looks like it was just a fluke? i kicked off the test again via empty commit and it passed 👍🏼

**Comment by goccy** [comment]
Thanks for the great PR !

**Comment by wass3r** [comment]
thanks for the speedy response and for the nice work on this library!

**Pull request merged**
